### ISSUE TITLE
d2 Interactive can't achieve, it seem just like a picture

### ISSUE THREAD

**Issue by cuilei0710** [BadgerHobbs/vitepress-plugin-d2#1]
![image](https://github.com/BadgerHobbs/vitepress-plugin-d2/assets/72482102/0f7a67d9-c630-49df-aaca-2c0dd33f0616)
when i use d2 playground, i hover the mouse on it and i got the Tooltips
![image](https://github.com/BadgerHobbs/vitepress-plugin-d2/assets/72482102/10b11114-a02b-4c8e-baaa-5f0efeafa988)
but this plugin seem like just convert code to svg, but can't interactive.

**Comment by BadgerHobbs** [comment]
Thanks for raising this. I was unaware of this interactive functionality in D2.

I am able to replicate your issue. It appears to be because the SVG is converted to base64 and then inserted as the source for an image element.

![image](https://github.com/BadgerHobbs/vitepress-plugin-d2/assets/23462440/b3aa1e8d-9af1-44a2-b14a-03cd17ab221f)

I shall look at creating a fix to use the SVG element itself instead of the base64 image.

**Comment by BadgerHobbs** [comment]
This issue should now be resolved with the latest release (1.0.3). Working on the [example site](https://badgerhobbs.github.io/vitepress-plugin-d2/#interactive-tooltips) as shown below.

![image](https://github.com/BadgerHobbs/vitepress-plugin-d2/assets/23462440/9e5f65b0-6bda-4268-91fd-3b15c58a0169)
